FROM node:22 AS builder
WORKDIR /app

RUN corepack enable

COPY pnpm-workspace.yaml pnpm-lock.yaml package.json ./

COPY lib/ ./lib/
COPY artifacts/api-server/ ./artifacts/api-server/

# Allow required native dependency build scripts
RUN pnpm config set only-built-dependencies esbuild,msedge-tts,onnxruntime-node,protobufjs,sharp

RUN pnpm install --frozen-lockfile

RUN pnpm --filter @workspace/api-server run build

RUN pnpm --filter @workspace/api-server deploy --prod /standalone


FROM node:22-alpine AS runner
WORKDIR /app

COPY --from=builder /standalone/node_modules ./node_modules
COPY --from=builder /app/artifacts/api-server/dist ./dist

ENV NODE_ENV=production

EXPOSE 8080

CMD ["node", "--enable-source-maps", "./dist/index.mjs"]